### PR TITLE
Updated Chunking Methods

### PR DESCRIPTION
**Pull request by PalmPalm7**
### Demonstrated new chunking methods in replace of RecursiveCharacterTextSplitter()

Notable updates:

1. Used a [efficient library](https://github.com/google/magika/tree/main) to detect file type.
2. Applied document-specific test splitter from Langchain in replace of original naive version.
3. Made heuristics changes to markdown file, especially using regex to trim markdown tables in attempt to fit in the whole table with limited context window.
4. For updated chunk_document() function, see [Chunking_Demo.ipynb](https://colab.research.google.com/drive/1lYHhhqQaOkKQCoFkhx0M7AT7N5UUvdRa?usp=sharing) on chunking with server_ctx_size=4096, chunk_word_count=1024). Granite 7b has 4k context windows.

### CODE REVIEW

**Comment by PalmPalm7** [comment]
> ### Demonstrated new chunking methods in replace of RecursiveCharacterTextSplitter()
> Notable updates:
> 
> 1. Used a [efficient library](https://github.com/google/magika/tree/main) to detect file type.
> 2. Applied document-specific test splitter from Langchain in replace of original naive version.
> 3. Made heuristics changes to markdown file, especially using regex to trim markdown tables in attempt to fit in the whole table with limited context window.
> 4. For updated chunk_document() function, see Chunking_Demo.ipynb on chunking with server_ctx_size=4096, chunk_word_count=1024). Granite 7b has 4k context windows.

@russellb @abhi1092  Hi Russel and Abhi, I have made final changes to the chunk_document() method and it passes all CI-Tests. Could you review my PR? Thanks

**Comment by russellb** [comment]
The code moved to `src/instructlab/sdg/utils/chunking.py`

**Comment by abhi1092** [comment]
A couple of things @PalmPalm7 :
* Is it assumed that if the file is not any of code file it always markdown?
* How do you handle chunks that are larger than the provided server_ctx_size ?

**Comment by PalmPalm7** [comment]
> A couple of things @PalmPalm7 :
> 
> * Is it assumed that if the file is not any of code file it always markdown?
> * How do you handle chunks that are larger than the provided server_ctx_size ?

Thank you for the review and the comments @abhi1092 ! 

1)
My Justification is there is I assume our most common use cases, as we discussed, is PDF into markdown formats, therefore default case should be markdown. Furthermore, by specifying the language param in RecursiveCharacterTextSplitter, it uses these following separators:
```
RecursiveCharacterTextSplitter.get_separators_for_language(Language.MARKDOWN)

Output:
['\n#{1,6} ',
 '```\n',
 '\n\\*\\*\\*+\n',
 '\n---+\n',
 '\n___+\n',
 '\n\n',
 '\n',
 ' ',
 '']
```

Instead of [these separators](https://github.com/instructlab/sdg/blob/1f71fb67aa46151bc0362e733b06529a1c609e6d/src/instructlab/sdg/utils/chunking.py#L41C1-L42C1).
 ```
["\n\n", "\n", " "]
```

2) 
This is valid concern. I have used the original chunk_document()'s logic, but it doesn't properly handle over context length chunk either.

**Comment by abhi1092** [comment]
Gotcha. Let's create an issue for `2.` so this can be addressed in the future. Everything looks good. 

Let me test this and we can merge it.

@PalmPalm7 could you resolve the the conflicts?


 But could you resolve the merge conflicts?

**Pull request closed without merging**
