### PR TITLE
Batch support with vllm 

### PR DESCRIPTION
**Pull request by aakankshaduggal**
This PR adds batch support with vllm

### CODE REVIEW

**Comment by russellb** [comment]
Can you rebase this PR on `main` so you don't have any merge commits in the PR branch?  thanks!

**Comment by aakankshaduggal** [comment]
Thanks @russellb, let's hold on to the reviews, we are still testing the changes. Will request the review once it is ready.

**Review by shivchander — APPROVED** [review]
tested offline - lgtm

**Review by oindrillac — APPROVED** [review]
Thanks @njhill @npalaska for adding VLLM support and @aakankshaduggal for testing this out

**Pull request merged**
