### PR TITLE
Rename instructlab.config to instructlab.configuration

### PR DESCRIPTION
**Pull request by russellb**
This changed in the instructlab repo, so match it.

Signed-off-by: Russell Bryant <rbryant@redhat.com>

### CODE REVIEW

**Review by cdoern — APPROVED** [review]
lgtm, thanks

**Comment by cdoern** [comment]
do we want to backport this :thinking:

**Comment by russellb** [comment]
> do we want to backport this 🤔

no - this is the `sdg` repo, it's fine

**Comment by russellb** [comment]
some more context -- the fact that this library is still importing stuff from `instructlab` is a bug tracked at #6 

We're just still in transition here so it's a bit messy ...

**Comment by cdoern** [comment]
oops, I need more coffee. I thought we were in a different repo :sweat_smile:

**Pull request merged**
