### PR TITLE
Data mix fix

### PR DESCRIPTION
**Pull request by aakankshaduggal**
Addresses #365

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@Mergifyio backport release-v0.3

**Review by bbrowning — APPROVED** [review]
Looks good to me - verified locally that this does add the pretraining samples into the phase10 dataset. I wrote a small unit test to verify this locally, so will create a follow-up PR to get that merged as well without blocking or adding to this one.

**Comment by aakankshaduggal** [comment]
Thanks @bbrowning for your review. I do have some tests in flight that I can add as a follow up PR.

**Comment by bbrowning** [comment]
Great - will hold off on turning my simple verification into an actual PR then and defer to you on that. Thanks for following up!

**Review by khaledsulayman — APPROVED** [review]
I've also tested this on an ec2 with full mixtral and looks good!

**Pull request merged**
