### PR TITLE
Remove the unnecessary SDG class

### PR DESCRIPTION
**Pull request by markmc**
Part of #61 and instructlab/dev-docs#113

A pipeline chains together a sequence of blocks, and an SDG chains together a sequence of pipelines. There is no need for this additional layer - we can construct a pipeline with the full sequence of blocks, and not chain pipelines together.

Check out how the API is used in `generate_data.py` to get a sense of the improvement

### CODE REVIEW

**Comment by russellb** [comment]
Assuming `e2e` passes, I am definitely supportive of this general direction. There's some discussion on #61 with @shivchander, so I'm not going to approve/merge just yet to give time for his input.

**Comment by markmc** [comment]
> Assuming `e2e` passes, I am definitely supportive of this general direction. There's some discussion on #61 with @shivchander, so I'm not going to approve/merge just yet to give time for his input.

The discussion has stalled for now

I've reduced the scope of this PR to just the `SDG` thing, since the rest is now incorporated into #86

**Review by russellb — APPROVED** [review]
I kicked off the CI job that runs the full pipeline.

Otherwise, this looks like a nice simplification to me.

**Review by hickeyma — COMMENTED** [review]
@shivchander you raised reasons for maintaining the SDG class in https://github.com/instructlab/sdg/issues/61#issuecomment-2203700941. What do you think of the changes in this PR?

**Comment by markmc** [comment]
See also instructlab/dev-docs#109

**Comment by hickeyma** [comment]
> See also https://github.com/instructlab/dev-docs/pull/109

@markmc do you mean https://github.com/instructlab/dev-docs/pull/113 instead?

**Comment by markmc** [comment]
> > See also [instructlab/dev-docs#109](https://github.com/instructlab/dev-docs/pull/109)
> 
> @markmc do you mean [instructlab/dev-docs#113](https://github.com/instructlab/dev-docs/pull/113) instead?

Doh, yes - thank you

**Review by hickeyma — COMMENTED** [review]
@markmc Is this blocked waiting on the design proposal to progress?

**Comment by markmc** [comment]
> @markmc Is this blocked waiting on the design proposal to progress?

Thanks for the reminder. I've rebased

I think the only blocker is that @shivchander has not yet acked [my YAGNI argument](https://github.com/instructlab/sdg/issues/61#issuecomment-2205460470)

**Comment by shivchander** [comment]
On the research side, we are actively working on developing complex flows that chain pipelines in a DAG fashion. Our goal with the SDG class wass to serve as an abstract wrapper capable of managing these complex flows.

Could this be renamed to something better? Yes. But I and the research team are not in favor of removing this, but I will not be blocker on this PR, If there's a consensus on moving forward. Just wanted to give a heads-up that at the pace research moves, we might need something which can handle this sooner.

**Comment by markmc** [comment]
> On the research side, we are actively working on developing complex flows that chain pipelines in a DAG fashion. Our goal with the SDG class wass to serve as an abstract wrapper capable of managing these complex flows.
> 
> Could this be renamed to something better? Yes. But I and the research team are not in favor of removing this, but I will not be a blocker on this PR, If there's a consensus on moving forward. Just wanted to give a heads-up that at the pace research moves, we might need something which can handle this sooner.

It's very difficult to remove an API once a library is starting to be used in the wild - and renaming an API is effectively removing an API. Library API maintainers need to be very careful about breaking downstream users. Removing an API generally involves a long deprecation period, to make sure users have time to migrate away from it.

I do not believe something called "SDG" will live on as the name of any abstraction in this library long-term, and I do not want to make it difficult to remove for no reason

Adding whatever the new abstraction should be is super easy, and made no more difficult by removing SDG

**Comment by markmc** [comment]
> It's very difficult to remove an API once a library is starting to be used in the wild - and renaming an API is effectively removing an API. Library API maintainers need to be very careful about breaking downstream users. Removing an API generally involves a long deprecation period, to make sure users have time to migrate away from it.

We will release 0.2.2 or 0.2.3 any day now, which will be used by instructlab 0.18.0, and from that point on I expect we'll be much more cautious about incompatible API changes. For that reason, I'm going to go ahead with this change despite objections, on the basis that it is trivial to restore this abstraction when we need it.

**Pull request merged**
