### PR TITLE
fix: e2e job using wrong flags

### PR DESCRIPTION
**Pull request by nathan-weinberg**
@instructlab/sdg-maintainers this job should be kept in alignment with https://github.com/instructlab/instructlab/blob/main/.github/workflows/e2e-nvidia-t4-x1.yml

### CODE REVIEW

**Review by cdoern — APPROVED** [review]
thanks

**Review by bbrowning — APPROVED** [review]

**Comment by bbrowning** [comment]
Is there a way to tell mergify to ignore the failing test here, since this change is supposed to fix that failing test? Or is this a case of we just need to merge it manually?

**Comment by cdoern** [comment]
@bbrowning I think its a manual merge situation. I have hit this weird dependency loop in instructlab before. Only way around it is to trigger custom runners.

**Review by khaledsulayman — APPROVED** [review]
Thanks for this, Nathan!

**Comment by bbrowning** [comment]
Ok, I manually merged and we'll verify this fixes the e2e the next time it gets triggered.

**Comment by bbrowning** [comment]
It looks like the e2e is passing again - thanks for the fix!

**Pull request merged**
